
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**

  jpa:
    open-in-view: true
    show-sql: true
    properties.hibernate:
      globally_quoted_identifiers: true

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: puser1
    password: puser1

server:
  port:


